### ISSUE TITLE
Cannot find module `vue-virtual-scroller/webpack.common.js`

### ISSUE THREAD

**Issue by skjnldsv** [Akryum/vue-virtual-scroller#172]
I have a weird error. I cannot import your package. I have a lot of others imports that works fine :woman_shrugging: 

```
ERROR in ./src/components/ContactsList.vue
Module build failed (from ./node_modules/eslint-loader/index.js):
Error: Cannot find module '/home/admin/Docker/apps2/contacts/node_modules/vue-virtual-scroller/webpack.common.js'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (/home/admin/Docker/apps2/contacts/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.exports.resolve (/home/admin/Docker/apps2/contacts/node_modules/eslint-import-resolver-webpack/index.js:70:27)
    at v2 (/home/admin/Docker/apps2/contacts/node_modules/eslint-module-utils/resolve.js:94:23)
    at withResolver (/home/admin/Docker/apps2/contacts/node_modules/eslint-module-utils/resolve.js:99:16)
    at fullResolve (/home/admin/Docker/apps2/contacts/node_modules/eslint-module-utils/resolve.js:116:22)
    at Function.relative (/home/admin/Docker/apps2/contacts/node_modules/eslint-module-utils/resolve.js:61:10)
    at remotePath (/home/admin/Docker/apps2/contacts/node_modules/eslint-plugin-import/lib/ExportMap.js:403:30)
    at captureDependency (/home/admin/Docker/apps2/contacts/node_modules/eslint-plugin-import/lib/ExportMap.js:432:15)
    at /home/admin/Docker/apps2/contacts/node_modules/eslint-plugin-import/lib/ExportMap.js:469:7
    at Array.forEach (<anonymous>)
    ...
```

**Comment by skjnldsv** [comment]
Ah, works if I import eh umd module 
`import { RecycleScroller } from 'vue-virtual-scroller/dist/vue-virtual-scroller.umd.js'`
