### ISSUE TITLE
Items overlap

### ISSUE THREAD

**Issue by simionato-mobisec** [Akryum/vue-virtual-scroller#828]
### Describe the bug

I followed what is written [here](https://github.com/Akryum/vue-virtual-scroller/tree/v1/packages/vue-virtual-scroller#dynamicscroller) to implement a dynamic scroller, but looks like the items overlap.

### Reproduction

MyDynamicScroller.vue
```
<template>
  <DynamicScroller
    style="height: 500px;"
    :items="items"
    :min-item-size="24"
  >
    <template #default="{ item, index, active }">
      <DynamicScrollerItem
        :item="item"
        :active="active"
        :size-dependencies="[item]"
        :data-index="index"
      >
        {{ `${index} ${item}` }}
      </DynamicScrollerItem>
    </template>
  </DynamicScroller>
</template>

<script>
export default {

  data() {
    return {
      items: []
    }
  },

  created() {
    this.findMessages()
  },

  methods: {

    findMessages() {
      MessageService.findAll().then(
        ({ data }) => {
          this.items = data
        },
        err => {
          console.log(err)
        }
      )
    }
  }
}
</script>
```
Messages have variable heights, with a min height of 24px. This is the output:
![scroller](https://github.com/Akryum/vue-virtual-scroller/assets/131374320/7e837808-06c9-4539-8eab-41d6ee54f414)
As you can see, items are overlapped (don't pay attention to weird chars).

### System Info

```shell
I'm using Vue2 on Firefox.
```

### Used Package Manager

npm

### Validations

- [X] Read the [docs](https://github.com/Akryum/vue-virtual-scroller/blob/master/packages/vue-virtual-scroller/README.md).
- [X] Check that there isn't [already an issue](https://github.com/Akryum/vue-virtual-scroller/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Akryum/vue-virtual-scroller/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by vsambor** [comment]
I had the same issue with the RecycleScroller, when the list changes sometimes (especially the first time, but not only) the items would overlap. 
And as a workaround I found that you have to recreate the entire component. This is how I did it. 

```
const shouldUpdateScroller = ref(true);

// When my list data updates
watch(list, () => {
    // Force scroller to refresh;
    shouldUpdateScroller.value = false;
    nextTick(() => {
        shouldUpdateScroller.value = true;
    });
});

// Then in the template

<RecycleScroller
                v-if="list.length > 0 && shouldUpdateScroller"
                ...
 />
 ```
 
 It's sad the lib is not maintained anymore :(

**Comment by Last-Dance-W** [comment]
I have also encountered such a problem ,Has it been resolved？

**Comment by CatherineAugustine** [comment]
Same issue here . Any solution?

**Comment by CatherineAugustine** [comment]
> I had the same issue with the RecycleScroller, when the list changes sometimes (especially the first time, but not only) the items would overlap. And as a workaround I found that you have to recreate the entire component. This is how I did it.
> 
> ```
> const shouldUpdateScroller = ref(true);
> 
> // When my list data updates
> watch(list, () => {
>     // Force scroller to refresh;
>     shouldUpdateScroller.value = false;
>     nextTick(() => {
>         shouldUpdateScroller.value = true;
>     });
> });
> 
> // Then in the template
> 
> <RecycleScroller
>                 v-if="list.length > 0 && shouldUpdateScroller"
>                 ...
>  />
> ```
> 
> It's sad the lib is not maintained anymore :(

This didnt help me

**Comment by vsambor** [comment]
@CatherineAugustine what do you experience? I'm surprised the workaround didn't help.

**Comment by CatherineAugustine** [comment]
> @CatherineAugustine what do you experience? I'm surprised the workaround didn't help. (can you share some of your code?)

 <RecycleScroller
          v-if="results && results.length > 0 && shouldUpdateScroller"
           :emit-update="true"
            page-mode
            :items="results"
            item-height="10"
            key-field="item"
            :item-size="5" :min-item-height="5"
            class="scroller"
            v-slot="{ item }"
          >
            <li  >
              {{  item  }}
            </li>
          </RecycleScroller>

My results are an array of string ['11111111','222222','33333333'] of upto 380k records

**Comment by vsambor** [comment]
@CatherineAugustine Try to do this first to see if it works:

```
<RecycleScroller
  v-if="results && results.length > 0 && shouldUpdateScroller"
    class="scroller"
    :items="results"
    :item-size="5" 
    v-slot="{ item, index }"
  >
    <li  >
      {{  item  }} {{ index }}
    </li>
</RecycleScroller>
```

Note you will have to modify your items to contain an id like items = [{id:0, text: '111111'}, {id:1, text: '22222'} ...]

If this works then try to add
`:page-mode="true"` and other things.

Note: by default the key-field is `id` so no need to specify

Also probably you have to much `height` props, for me just setting the `item-size` was enough. 

Good luck and let me know if it works for you.

**Comment by CatherineAugustine** [comment]
Sadly, adding the id didn't help.

One thing I noticed is that, if I remove the ` v-if="results && results.length > 0 && shouldUpdateScroller"` condition, the overlapping is gone, but the dropdown doesn't repaint when the results are modified, though I have declared the results field reactive.

**Comment by CatherineAugustine** [comment]
Seeing a different error this time

runtime-core.esm-bundler.js:265 Uncaught Error: Rendered items limit reached
    at Proxy.itemsLimitError (RecycleScroller.vue:756:13)
    at Proxy.updateVisibleItems (RecycleScroller.vue:504:14)
    at Proxy.handleResize (RecycleScroller.vue:343:28)
    at callWithErrorHandling (runtime-core.esm-bundler.js:195:19)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:202:17)
    at emit (runtime-core.esm-bundler.js:726:5)
    at Proxy.emitSize (ResizeObserver.vue:83:12)
    at Proxy.compareAndNotify (ResizeObserver.vue:78:14)
    at Proxy.addResizeHandlers (ResizeObserver.vue:91:12)

**Comment by vsambor** [comment]
I would like to see your example, to try it more. Could you create a reproducible example like in stackblitz or somewhere?
I have the same version as you `"vue-virtual-scroller": "^2.0.0-beta.8"` and It works for me.

**Comment by CatherineAugustine** [comment]
` :item-size="5" `

property needs to be looked into for overlapping values. I changed it to 30 and it worked fine .

**Comment by vsambor** [comment]
Happy it works for you, I didn't pay attention that you used 5 px :) 
All the best!

**Comment by linshujuan** [comment]
> perty needs to be looked into for overlapping values. I chang

Thanks! It works for me, the array must have id, the key-field to other field will occur issue

**Comment by sxlisme** [comment]
When will this bug be fixed？

**Comment by Akryum** [comment]
Please comment if still an issue with latest version.
